---
- name: Setup Common Components
  hosts: masters,nodes
  roles:
    - common
    - docker
    - k8s-base

- name: Setup Kubernetes Masters
  hosts: masters
  roles:
    - haproxy
    - keepalived
    - k8s-master

- name: Setup Kubernetes Nodes
  hosts: nodes
  roles:
    - k8s-node

- name: Configure Kubernetes Cluster
  hosts: masters[0]
  roles:
    - calico-network
    - k8s-completion
    - cert-manager
    - cluster-validation
