# roles/k8s-base/tasks/main.yml
---
- name: Create directory for Kubernetes keyring
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Remove old GPG key (if exists)
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: absent

# 使用變數版本下載 GPG key
- name: Download Kubernetes GPG key
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_gpg_key_version }}/deb/Release.key"
    dest: /tmp/k8s-archive-keyring.key
    mode: '0644'

- name: Import Kubernetes GPG key
  shell: cat /tmp/k8s-archive-keyring.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Set proper permissions for GPG key
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'

# 使用變數版本配置倉庫
- name: Add Kubernetes Repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_repo_version }}/deb/ /"
    state: present
    filename: kubernetes
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name:
      - "kubelet={{ k8s_version }}"
      - "kubeadm={{ k8s_version }}"
      - "kubectl={{ k8s_version }}"
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Download cri-dockerd deb package
  get_url:
    url: "https://github.com/Mirantis/cri-dockerd/releases/download/v{{ cri_dockerd_version }}/cri-dockerd_{{ cri_dockerd_version }}.{{ ansible_distribution_release }}_{{ ansible_architecture }}.deb"
    dest: "/tmp/cri-dockerd.deb"

- name: Install cri-dockerd
  apt:
    deb: /tmp/cri-dockerd.deb
    state: present

- name: Create kubelet config directory
  file:
    path: /etc/default
    state: directory
    mode: '0755'

- name: Configure kubelet
  template:
    src: kubelet.conf.j2
    dest: /etc/default/kubelet
  notify: Restart kubelet

- name: Enable and start kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Enable and start cri-docker service
  service:
    name: cri-docker
    state: started
    enabled: yes
