---
# 第一個 master 節點的任務
- name: First master node tasks
  block:
    - name: Generate kubeadm config
      template:
        src: kubeadm.yaml.j2
        dest: /root/kubeadm.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Pull required images
      command: kubeadm config images pull --config /root/kubeadm.yaml
      register: pull_images
      retries: 3
      delay: 5
      until: pull_images is success

    - name: Initialize first master node
      command: kubeadm init --config /root/kubeadm.yaml --upload-certs
      register: kubeadm_init
      failed_when: 
        - kubeadm_init.rc != 0
        - "'already exists' not in kubeadm_init.stderr"

    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        mode: '0644'

    - name: Get join command for other masters
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Get certificate key
      command: kubeadm init phase upload-certs --upload-certs
      register: cert_key

    - name: Save join command and cert key
      set_fact:
        join_command: "{{ join_command.stdout }}"
        cert_key: "{{ cert_key.stdout_lines[-1] }}"

    - name: Wait for apiserver
      wait_for:
        host: "{{ ansible_host }}"
        port: 6443
        timeout: 300

  when: inventory_hostname == groups['masters'][0]

# 其他 master 節點的任務
- name: Other master nodes tasks
  block:
    - name: Join other master nodes
      command: >
        {{ hostvars[groups['masters'][0]]['join_command'] }}
        --control-plane
        --certificate-key {{ hostvars[groups['masters'][0]]['cert_key'] }}
        --cri-socket=unix:///var/run/cri-dockerd.sock
      register: join_masters
      retries: 3
      delay: 10
      until: join_masters is success
      failed_when:
        - join_masters.rc != 0
        - "'already exists' not in join_masters.stderr"

    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        mode: '0644'

  when: inventory_hostname != groups['masters'][0]
