---
# Kubernetes 版本配置
k8s_version: 1.26.15-1.1                     # 安裝的 K8s 套件版本
k8s_gpg_key_version: v1.31                   # 用於下載 GPG key 的版本
k8s_repo_version: v1.26                      # 用於配置 apt 倉庫的版本
kubernetes_version: v1.26.15                  # 用於 kubeadm 配置的版本(不含發行版本號)

# Kubernetes 網路配置
pod_network_cidr: 10.244.0.0/16
service_network_cidr: 10.245.0.0/16
cluster_name: kubernetes
calico_version: v3.26.0

# Docker 配置
docker_version: 5:20.10.13~3-0~ubuntu-jammy
cri_dockerd_version: 0.3.3.3-0

# 系統配置
network_interface: ens160
master_lb_priority: 101
keepalived_router_id: 60
keepalived_auth_pass: K8SHA_KA_AUTH

# 節點配置
k8s_master_nodes:
  master1:
    name: "{{ master1_hostname }}"
    ip: "{{ master1_ip }}"
  master2:
    name: "{{ master2_hostname }}"
    ip: "{{ master2_ip }}"
  master3:
    name: "{{ master3_hostname }}"
    ip: "{{ master3_ip }}"

k8s_worker_nodes:
  worker1:
    name: "{{ worker1_hostname }}"
    ip: "{{ worker1_ip }}"
  worker2:
    name: "{{ worker2_hostname }}"
    ip: "{{ worker2_ip }}"

# LoadBalancer 配置
k8s_lb:
  vip: "{{ vip_ip }}"
  port: "{{ vip_port }}"

# Kubeadm 配置
kubeadm_token: "7t2weq.bjbawausm0jaxury"

# Docker 變數配置
docker_config:
  version: "5:20.10.13~3-0~ubuntu-jammy"
  data_root: "/var/lib/docker"
  log_max_size: "100m"
  log_max_file: "3"
  registry_mirrors:
    - "https://registry.docker-cn.com"
    - "https://docker.mirrors.ustc.edu.cn"
  insecure_registries: []

# Kubernetes 變數配置
kubernetes_config:
  version: "1.26.3-00"
  cri_dockerd_version: "0.3.3.3-0"
  pod_infra_container_image: "registry.k8s.io/pause:3.9"
  cgroup_driver: "systemd"
  cluster_dns: "10.96.0.10"
  cluster_domain: "cluster.local"
  node_ip: "{{ ansible_default_ipv4.address }}"

# HAProxy 和 Keepalived 變數配置
haproxy_config:
  maxconn: 2000
  monitor_port: 33305
  timeout:
    connect: 5000
    client: 50000
    server: 50000
    http_request: 15s
    http_keep_alive: 15s

keepalived_config:
  router_id: "LVS_DEVEL"
  virtual_router_id: 60
  priority: 101
  check_interval: 5
  check_weight: -5
  check_fall: 2
  check_rise: 1
  advert_int: 1
  auth_pass: "K8SHA_KA_AUTH"
  vip_netmask: 24
  smtp_alerts: false
  smtp_server: "localhost"
  notification_email: []
  notification_email_from: ""
  notify_scripts: false

# Kubernetes Master/Node 變數配置
k8s_master_config:
  image_repository: registry.k8s.io
  service_cidr: 10.96.0.0/12
  pod_network_provider: calico
  control_plane_endpoint_port: 6443
  certificates_dir: /etc/kubernetes/pki
  etcd_data_dir: /var/lib/etcd
  admission_plugins:
    - NodeRestriction
  extra_args:
    apiserver: {}
    controller_manager:
      bind-address: 0.0.0.0
    scheduler:
      bind-address: 0.0.0.0

k8s_node_config:
  kubelet_extra_args: {}
  labels: {}
  taints: []

# Calico 變數配置
network_config:
  calico_version: v3.26.0
  pod_network_cidr: 10.244.0.0/16
  calico:
    registry: docker.io
    image_path: calico
    block_size: 26
    encapsulation: VXLANCrossSubnet
    nat_outgoing: Enabled
    node_selector: all()
    ip_autodetection_method: "interface={{ network_interface }}"
    container_ip_forwarding: Disabled
    enable_wireguard: false
    mtu: 1440
    felix_config:
      logSeverityScreen: Info
    typha_config:
      enabled: true
      replicas: 3

# k8s_tools_config 變數配置
k8s_tools_config:
  completion:
    enable_aliases: true
    custom_aliases:
      kc: kubectl
      kns: kubectl config set-context --current --namespace
  cert_manager:
    backup_dir: /etc/kubernetes/pki/backup
    update_repo: https://github.com/yuyicai/update-kube-cert.git
    update_version: master
    validity_years: 10
    wait_timeout: 300

# validation 變數配置
validation:
  timeout: 300
  retries: 6
  delay: 10
  test:
    namespace: validation-test
    pod_name: test-nginx
    service_name: test-nginx
    dns_pod_name: dns-test
    image: nginx:alpine
    dns_image: busybox:1.28
  cleanup: true
  report_dir: /var/log/kubernetes/validation
