---
- name: Verify master node is ready
  wait_for:
    host: "{{ k8s_lb.vip }}"
    port: "{{ k8s_lb.port }}"
    timeout: 300
  delegate_to: localhost

- name: Join worker nodes
  command: >
    {{ hostvars[groups['masters'][0]]['join_command'] }}
    --cri-socket=unix:///var/run/cri-dockerd.sock
  register: node_join
  retries: 3
  delay: 10
  until: node_join is success
  failed_when:
    - node_join.rc != 0
    - "'already exists' not in node_join.stderr"

- name: Wait for node to be ready
  command: kubectl get nodes {{ inventory_hostname }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
  register: node_status
  until: node_status.stdout == "True"
  retries: 30
  delay: 10
  delegate_to: "{{ groups['masters'][0] }}"
  changed_when: false
