---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
      - net-tools
      - ntp
      - wget
    state: present

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Disable UFW
  service:
    name: ufw
    state: stopped
    enabled: no

- name: Disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable swap
  command: swapoff -a
  changed_when: false

- name: Load kernel modules
  template:
    src: k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf
  notify: Reload systemd modules

- name: Apply kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Set kernel parameters
  template:
    src: sysctl-k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
  notify: Apply sysctl

- name: Install IPVS packages
  apt:
    name:
      - ipvsadm
      - ipset
      - sysstat
      - conntrack
      - libseccomp2
      - libseccomp-dev
    state: present

- name: Load IPVS modules
  template:
    src: ipvs.conf.j2
    dest: /etc/modules-load.d/ipvs.conf
  notify: Reload systemd modules

- name: Apply IPVS modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack

- name: Enable transparent masquerading
  modprobe:
    name: br_netfilter
    state: present

- name: Sync time with NTP servers
  service:
    name: ntp
    state: started
    enabled: yes

- name: Create kubernetes directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/kubernetes
    - /etc/kubernetes/manifests
    - /var/lib/kubelet
    - /var/lib/etcd
