---
all:
  children:
    masters:
      hosts:
        "{{ master1_hostname }}":
          ansible_host: "{{ master1_ip }}"
        "{{ master2_hostname }}":
          ansible_host: "{{ master2_ip }}"
        "{{ master3_hostname }}":
          ansible_host: "{{ master3_ip }}"
    nodes:
      hosts:
        "{{ worker1_hostname }}":
          ansible_host: "{{ worker1_ip }}"
        "{{ worker2_hostname }}":
          ansible_host: "{{ worker2_ip }}"
  vars:
    ansible_user: root
    # Master 節點配置
    master1_hostname: k8s-master71
    master1_ip: 192.168.1.71
    master2_hostname: k8s-master72
    master2_ip: 192.168.1.72
    master3_hostname: k8s-master73
    master3_ip: 192.168.1.73
    # Worker 節點配置
    worker1_hostname: k8s-node75
    worker1_ip: 192.168.1.75
    worker2_hostname: k8s-node76
    worker2_ip: 192.168.1.76
    # VIP 配置
    vip_ip: 192.168.1.74
    vip_port: 7443
