---
- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Create HAProxy configuration directory
  file:
    path: /etc/haproxy
    state: directory
    mode: '0755'

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart haproxy

- name: Create HAProxy default file
  template:
    src: haproxy.default.j2
    dest: /etc/default/haproxy
    owner: root
    group: root
    mode: '0644'
  notify: Restart haproxy

- name: Enable and start HAProxy service
  service:
    name: haproxy
    state: started
    enabled: yes
